server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Hỗ trợ React Router (Fallback về index.html nếu không tìm thấy đường dẫn)
        try_files $uri $uri/ /index.html;
    }

    # Bỏ qua log với favicon hoặc robots.txt
    location = /favicon.ico { log_not_found off; access_log off; }
    location = /robots.txt  { log_not_found off; access_log off; }
}
