version: '3.8'

services:
  # CSDL chung cho toàn bộ app
  mongodb:
    image: mongo:latest
    container_name: food_mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - food-network

  # 1. User Service
  user-service:
    build: ./user-service
    container_name: food_user_service
    environment:
      - MONGO_URI=mongodb://mongodb:27017/food_ordering_users
      - DATA_INIT_ENABLED=true
    depends_on:
      - mongodb
    networks:
      - food-network

  # 2. Food Service
  # Run on remote host:
  # http://172.28.62.165:8082

  # 3. Order Service
  order-service:
    build: ./order-service
    container_name: food_order_service
    environment:
      - MONGO_URI=mongodb://mongodb:27017/food_ordering_orders
      - USER_SERVICE_URL=http://152.42.169.250:8081
      - FOOD_SERVICE_URL=http://172.28.62.165:8082
    depends_on:
      - mongodb
      - user-service
    networks:
      - food-network

  # 4. Payment Service
  # Run on remote host:
  # http://172.28.62.165:8084

  # 5. Notification Service
  # Run on remote host:
  # http://172.28.62.165:8085

  # 0. API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: food_api_gateway
    ports:
      - "8080:8080"
    environment:
      - USER_SERVICE_URL=http://152.42.169.250:8081
      - FOOD_SERVICE_URL=http://172.28.62.165:8082
      - ORDER_SERVICE_URL=http://152.42.169.250:8083
      - PAYMENT_SERVICE_URL=http://172.28.62.165:8084
    depends_on:
      - user-service
      - order-service
    networks:
      - food-network

  # 6. Frontend
  frontend:
    build:
      context: ./frontend
      # Hardcode API Gateway public URL for deployment.
      args:
        - VITE_USER_SERVICE_URL=http://152.42.169.250:8080
        - VITE_FOOD_SERVICE_URL=http://152.42.169.250:8080
        - VITE_ORDER_SERVICE_URL=http://152.42.169.250:8080
        - VITE_PAYMENT_SERVICE_URL=http://152.42.169.250:8080
    container_name: food_frontend
    ports:
      - "5173:80"
    depends_on:
      - api-gateway
    networks:
      - food-network

networks:
  food-network:
    driver: bridge

volumes:
  mongodb_data:
