server:
  port: 8085

spring:
  application:
    name: notification-service

logging:
  level:
    root: INFO
    com.foodorder.notificationservice: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
